

server:
  servlet:
    session:
      timeout: PT10M # 十分钟，默认是30m
#    context-path: /webrtc # 前缀
  port: 8010
# 默认的log配置
logging:
  level:
    root: INFO
  root:
    appender: Console
    path: .

rest:
  stun:
    url: http://webrtc-test.quantil.com:2018/p2p-proxy
    # ms
    readTimeout: 300000
    connectTimeout: 300000
    retryCount: 3
    ssl:
      protocols: TLSv1.2


spring:
  http:
    encoding: utf-8
  application:
    name: webrtc
  datasource:
    sql:
      initialSize: 10
      minIdle: 10
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 150000
      validationQuery: SELECT 1
      validationQueryTimeout: 3600
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

  freemarker:
    content-type: text/html
    template-loader-path: classpath:/static
    suffix: .html
    cache: false
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
#      classic_compatible: true


filter:
  url:
    # 所有的配置都以杠号开头
    # rest 是api请求,加上前缀以后，api请求就是/rest/...
    # js,css这些是静态数据
    excludedPatterns : /**/*.js,/**/*.css # 不需要认证可以直接访问的url，使用ant pattern表达式
    login: /p/user/login



