

server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: Quantil#2020

logging:
  level:
    root: INFO
  #    com.quantil: DEBUG
  root:
    appender: RollingFile
    path: .

spring:
  datasource:
    sql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://qa.db.host:63751/web_rtc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: mileweb2016!@#
